version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=test
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - .:/scripts
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f scripts/data.cql"

  web:
    build: .
    environment:
      - CASANDRA_HOST=cassandra
    depends_on:
      - cassandra-load-keyspace
    volumes:
      - .:/code
    ports:
      - "8000:8000"